// src/components/PrescriptionAnalyzerStandalone.jsx
import React, { useState, useCallback } from 'react';
import { Upload, FileText, AlertTriangle, CheckCircle, X, Loader, Download, Eye } from 'lucide-react';
import { useLocalizationStore } from '../store';
import { translations } from '../translations';

const PrescriptionAnalyzerStandalone = () => {
  const [file, setFile] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [dragActive, setDragActive] = useState(false);
  
  const { currentLanguage } = useLocalizationStore();
  
  // Translation function
  const t = (key, fallback = key) => {
    const translation = translations[currentLanguage]?.[key];
    return translation || fallback;
  };

  const handleDrag = useCallback((e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  }, []);

  const handleFileSelect = (selectedFile) => {
    // Check file type
    if (!selectedFile.type.includes('pdf') && !selectedFile.name.endsWith('.txt')) {
      alert(t('prescription_analyzer_invalid_file_type', 'Please upload PDF or TXT files only'));
      return;
    }
    
    // Check file size (max 10MB)
    if (selectedFile.size > 10 * 1024 * 1024) {
      alert(t('prescription_analyzer_file_too_large', 'File size should be less than 10MB'));
      return;
    }
    
    setFile(selectedFile);
    setAnalysisResult(null);
  };

  const analyzeDocument = async () => {
    if (!file) return;
    
    setIsAnalyzing(true);
    
    try {
      // Simulate API call for demo
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Demo analysis result with comprehensive prescription information
      const demoResult = {
        medications_found: [
          'Metformin 500mg - Twice daily with meals',
          'Lisinopril 10mg - Once daily in morning',
          'Atorvastatin 20mg - Once daily at bedtime'
        ],
        red_flags: [
          {
            flag: 'Drug Interaction Alert',
            severity: 'medium',
            description: 'Monitor for potential interaction between Lisinopril and potassium supplements. Regular electrolyte monitoring recommended.'
          },
          {
            flag: 'Dosage Verification Required',
            severity: 'low',
            description: 'Verify Metformin dosage based on current kidney function (eGFR). May require adjustment if renal function is impaired.'
          }
        ],
        recommendations: [
          'Take Metformin with food to reduce gastrointestinal side effects',
          'Monitor blood pressure regularly while on Lisinopril therapy',
          'Schedule liver function tests every 6 months for Atorvastatin monitoring',
          'Consider medication timing optimization for better therapeutic outcomes',
          'Maintain regular follow-up appointments for medication effectiveness assessment'
        ],
        ai_analysis: {
          summary: 'This prescription contains a comprehensive diabetes and cardiovascular management regimen. The combination of Metformin (diabetes), Lisinopril (blood pressure), and Atorvastatin (cholesterol) is commonly prescribed for metabolic syndrome management. All medications are generally safe when used together but require regular monitoring for optimal therapeutic outcomes and to prevent potential adverse effects.'
        }
      };
      
      setAnalysisResult(demoResult);
    } catch (error) {
      console.error('Analysis error:', error);
      alert(t('prescription_analyzer_error', 'Analysis failed. Please try again.'));
    } finally {
      setIsAnalyzing(false);
    }
  };

  const getSeverityColor = (severity) => {
    switch (severity) {
      case 'high': return 'text-red-600 bg-red-50 border-red-200';
      case 'medium': return 'text-orange-600 bg-orange-50 border-orange-200';
      case 'low': return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      default: return 'text-gray-600 bg-gray-50 border-gray-200';
    }
  };

  const getSeverityIcon = (severity) => {
    switch (severity) {
      case 'high': return <AlertTriangle className="w-5 h-5 text-red-500" />;
      case 'medium': return <AlertTriangle className="w-5 h-5 text-orange-500" />;
      case 'low': return <Eye className="w-5 h-5 text-yellow-500" />;
      default: return <CheckCircle className="w-5 h-5 text-green-500" />;
    }
  };

  const downloadReport = () => {
    if (!analysisResult) return;
    
    const report = `
PRESCRIPTION ANALYSIS REPORT
Generated by Vaidya Dhara - RISHI AI
Date: ${new Date().toLocaleDateString()}

MEDICATIONS IDENTIFIED:
${analysisResult.medications_found?.map(med => `• ${med}`).join('\n')}

SAFETY ALERTS:
${analysisResult.red_flags?.map(flag => `• ${flag.flag} (${flag.severity.toUpperCase()}): ${flag.description}`).join('\n')}

HEALTHCARE RECOMMENDATIONS:
${analysisResult.recommendations?.map(rec => `• ${rec}`).join('\n')}

RISHI AI ANALYSIS:
${analysisResult.ai_analysis?.summary || 'No AI analysis available'}

IMPORTANT DISCLAIMER:
This analysis is for informational purposes only and should not replace professional medical advice. 
Always consult with qualified healthcare professionals regarding your medications, dosages, and treatment plans. 
Do not make changes to your medication regimen without proper medical supervision.

Generated by Vaidya Dhara Health Platform
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prescription-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Main Upload Card - Professional Layout */}
      <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
        {/* Header */}
        <div className="bg-slate-50 px-6 py-4 border-b border-slate-200">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-blue-100 rounded-lg">
              <FileText className="w-6 h-6 text-blue-600" />
            </div>
            <h2 className="text-xl font-semibold text-slate-900">
              {t('prescription_analyzer_title', 'Prescription Analyzer')}
            </h2>
          </div>
        </div>

        {/* Upload Content */}
        <div className="p-8">
          {!file ? (
            <div
              className={`border-2 border-dashed rounded-xl p-12 text-center transition-all duration-200 ${
                dragActive 
                  ? 'border-blue-500 bg-blue-50 scale-[1.02]' 
                  : 'border-slate-300 hover:border-blue-400 hover:bg-slate-50'
              }`}
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={(e) => {
                e.preventDefault();
                setDragActive(false);
                const droppedFile = e.dataTransfer.files[0];
                if (droppedFile) handleFileSelect(droppedFile);
              }}
            >
              <div className="mb-6">
                <Upload className={`w-16 h-16 mx-auto mb-4 transition-colors ${
                  dragActive ? 'text-blue-500' : 'text-slate-400'
                }`} />
                <h3 className="text-xl font-semibold text-slate-900 mb-3">
                  {t('prescription_analyzer_upload_title', 'Upload Prescription')}
                </h3>
                <p className="text-slate-600 text-lg max-w-md mx-auto">
                  {t('prescription_analyzer_upload_desc', 'Drag and drop your prescription here, or click to browse')}
                </p>
              </div>
              
              <input
                type="file"
                accept=".pdf,.txt"
                onChange={(e) => {
                  const selectedFile = e.target.files[0];
                  if (selectedFile) handleFileSelect(selectedFile);
                }}
                className="hidden"
                id="file-upload"
              />
              <label
                htmlFor="file-upload"
                className="inline-flex items-center gap-3 px-8 py-3 bg-blue-600 text-white text-lg font-medium rounded-lg hover:bg-blue-700 cursor-pointer transition-colors shadow-md hover:shadow-lg"
              >
                <Upload className="w-5 h-5" />
                {t('prescription_analyzer_browse', 'Browse Files')}
              </label>
              
              <p className="text-sm text-slate-500 mt-4 flex items-center justify-center gap-2">
                <FileText className="w-4 h-4" />
                {t('prescription_analyzer_file_types', 'Supports PDF and TXT files (max 10MB)')}
              </p>
            </div>
          ) : (
            <div className="space-y-6">
              {/* Selected File Display */}
              <div className="flex items-center justify-between p-6 bg-slate-50 rounded-xl border border-slate-200">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-blue-100 rounded-lg">
                    <FileText className="w-6 h-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="font-semibold text-slate-900 text-lg">{file.name}</p>
                    <p className="text-slate-600">
                      {(file.size / 1024 / 1024).toFixed(2)} MB • {file.type || 'Unknown type'}
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => {
                    setFile(null);
                    setAnalysisResult(null);
                  }}
                  className="p-2 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
              
              {/* Analyze Button */}
              <button
                onClick={analyzeDocument}
                disabled={isAnalyzing}
                className="w-full bg-blue-600 text-white py-4 px-6 rounded-xl hover:bg-blue-700 disabled:bg-slate-400 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-3 text-lg font-medium shadow-md hover:shadow-lg"
              >
                {isAnalyzing ? (
                  <>
                    <Loader className="w-5 h-5 animate-spin" />
                    {t('prescription_analyzer_analyzing', 'Analyzing Prescription...')}
                  </>
                ) : (
                  <>
                    <FileText className="w-5 h-5" />
                    {t('prescription_analyzer_analyze', 'Analyze Prescription')}
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Comprehensive Analysis Results */}
      {analysisResult && (
        <div className="space-y-6">
          {/* Results Header */}
          <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-green-100 rounded-lg">
                  <CheckCircle className="w-6 h-6 text-green-600" />
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-slate-900">
                    {t('prescription_analyzer_results', 'Prescription Analysis Complete')}
                  </h3>
                  <p className="text-slate-600">
                    {t('prescription_analyzer_results_desc', 'Comprehensive analysis of your prescription')}
                  </p>
                </div>
              </div>
              <button
                onClick={downloadReport}
                className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors shadow-md"
              >
                <Download className="w-4 h-4" />
                {t('prescription_analyzer_download', 'Download Report')}
              </button>
            </div>

            {/* Key Metrics */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-blue-50 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-2">
                  <FileText className="w-5 h-5 text-blue-600" />
                  <span className="text-sm font-medium text-blue-700">Medications</span>
                </div>
                <p className="text-2xl font-bold text-blue-900">
                  {analysisResult.medications_found?.length || 0}
                </p>
              </div>
              <div className="bg-orange-50 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="w-5 h-5 text-orange-600" />
                  <span className="text-sm font-medium text-orange-700">Alerts</span>
                </div>
                <p className="text-2xl font-bold text-orange-900">
                  {analysisResult.red_flags?.length || 0}
                </p>
              </div>
              <div className="bg-green-50 rounded-lg p-4">
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                  <span className="text-sm font-medium text-green-700">Recommendations</span>
                </div>
                <p className="text-2xl font-bold text-green-900">
                  {analysisResult.recommendations?.length || 0}
                </p>
              </div>
            </div>
          </div>

          {/* Prescription Details */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Medications Found */}
            {analysisResult.medications_found && analysisResult.medications_found.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
                <h4 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
                  <FileText className="w-5 h-5 text-blue-600" />
                  {t('prescription_analyzer_medications', 'Prescribed Medications')}
                </h4>
                <div className="space-y-3">
                  {analysisResult.medications_found.map((medication, index) => (
                    <div key={index} className="flex items-start gap-3 p-3 bg-blue-50 rounded-lg">
                      <div className="w-2 h-2 bg-blue-600 rounded-full mt-2"></div>
                      <div className="flex-1">
                        <p className="font-medium text-blue-900">{medication}</p>
                        <p className="text-sm text-blue-700 mt-1">
                          Active pharmaceutical ingredient identified
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Safety Information */}
            {analysisResult.red_flags && analysisResult.red_flags.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
                <h4 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-orange-600" />
                  {t('prescription_analyzer_alerts', 'Safety Alerts')}
                </h4>
                <div className="space-y-3">
                  {analysisResult.red_flags.map((flag, index) => (
                    <div key={index} className={`p-4 rounded-lg border-l-4 ${getSeverityColor(flag.severity)}`}>
                      <div className="flex items-start gap-3">
                        {getSeverityIcon(flag.severity)}
                        <div className="flex-1">
                          <h5 className="font-medium text-sm uppercase tracking-wide opacity-75">
                            {flag.severity} Priority
                          </h5>
                          <p className="font-semibold mt-1">{flag.flag}</p>
                          <p className="text-sm mt-2 opacity-90">{flag.description}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Recommendations & AI Analysis */}
          <div className="space-y-6">
            {/* Recommendations */}
            {analysisResult.recommendations && analysisResult.recommendations.length > 0 && (
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
                <h4 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-green-600" />
                  {t('prescription_analyzer_recommendations', 'Healthcare Recommendations')}
                </h4>
                <div className="grid gap-3">
                  {analysisResult.recommendations.map((rec, index) => (
                    <div key={index} className="flex items-start gap-3 p-4 bg-green-50 rounded-lg border border-green-100">
                      <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
                      <p className="text-green-900 font-medium">{rec}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* AI Analysis Summary */}
            {analysisResult.ai_analysis && (
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
                <h4 className="text-lg font-semibold text-slate-900 mb-4 flex items-center gap-2">
                  <Eye className="w-5 h-5 text-purple-600" />
                  {t('prescription_analyzer_ai_analysis', 'RISHI AI Analysis')}
                </h4>
                <div className="bg-purple-50 rounded-lg p-4 border border-purple-100">
                  <p className="text-purple-900 leading-relaxed">
                    {analysisResult.ai_analysis.summary || analysisResult.ai_analysis}
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Medical Disclaimer */}
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-6">
            <div className="flex items-start gap-3">
              <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0 mt-1" />
              <div>
                <h5 className="font-semibold text-amber-900 mb-2">Important Medical Disclaimer</h5>
                <p className="text-amber-800 text-sm leading-relaxed">
                  This analysis is for informational purposes only and should not replace professional medical advice. 
                  Always consult with qualified healthcare professionals regarding your medications, dosages, and treatment plans. 
                  Do not make changes to your medication regimen without proper medical supervision.
                </p>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PrescriptionAnalyzerStandalone;
